# الخط الذي قمنا بتثبيته
font_family      MesloLGS NF
font_size        12.0

# الشفافية (0.8 تعني شفاف بنسبة 20%)
background_opacity 0.8
confirm_os_window_close 0

# ألوان متناسقة مع الثيم الزجاجي
foreground #cdd6f4
background #1e1e2e
